export const ACK_EVENTS = [
    "ALARM_SET",
    "ALARM_RING",
    "ALARM_STOP",
    "DEVICE_OFF",
    "DEVICE_RESET",
    "DEVICE_RESTART",
    "PING_DEVICE_UP",
    "DEVICE_CONFIGURE",
    "REMINDER_NOTIFY",
]